version: "3"

services:
  app:
    image: oyapp:lastest
    build: .
    #environment:
    #  - DISPLAY=${DISPLAY}
    env_file:
      - .env
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    network_mode: host
